---
AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
Style/EvalWithLocation:
  Enabled: false
Security/Eval:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false